### PR TITLE
Make models optional to return from the model decorator

### PR DESCRIPTION
**Pull request by volkangurel**
Make models optional to return from the model decorator.

This should address https://github.com/layerai/sdk/issues/244 by letting users return `None` from their training runs without impacting Layer successfully finishing a training run and collecting metadata.

### CODE REVIEW

**Review by eminn — COMMENTED** [review]
Did we check how the UI would be broken by the missing fields from a successful train ?

**Comment by volkangurel** [comment]
Yep, the UI looks good:
image

**Comment by volkangurel** [comment]
Sorry, here's the one without a returned model. Still looks good :
image

**Review by eminn — APPROVED** [review]

**Comment by fcakyon** [comment]
@volkangurel is there a way to log model via logging api? Something like `layer.log_model(model)` or `layer.log(model)`?

**Comment by fcakyon** [comment]
got my answer its `save_model` :+1:

**Pull request merged**
